name: Test on Latest Dev Falco
on:
  workflow_dispatch:
    inputs:
      version:
        description: Falco Version
        default: master
        required: true

jobs:
  build:
    name: Run Tests on Falco
    runs-on: ubuntu-latest
    container:
      image: falcosecurity/falco:${{ github.event.inputs.version }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'

      - name: Checkout repo ⤵️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install go-junit-report
        run: |
          go install github.com/jstemmer/go-junit-report/v2@latest
  
      - name: Run Go Generate
        run: |
          go generate ./...

      - name: Run Go Tests
        run: |
          go test -json ./tests/... 2>&1 | go-junit-report -parser gojson > report.xml

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "report.xml"
        if: always()
